
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rog
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjobs/publish_scheduled.yaml
  - cronjobs/daily_email_sender.yaml
  - cronjobs/resend_data_to_pantheon.yaml
  # - cronjobs/sync_consul_users.yaml
images:
  - name: rog
    newName: rg.fr-par.scw.cloud/djnd/rog
    newTag: '7e9bae82839137b30715c9d9a266e0ce508c3f6e'
